branch-defaults:
  default:
    environment: fyyur-env
  fyyur_branch:
    environment: fyyur-env
  master:
    environment: fyyur-env
environment-defaults:
  fyyur-env:
    branch: null
    repository: null
global:
  application_name: fyyur
  branch: fyyur_branch
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
