"""empty message

Revision ID: 270413bf4fa4
Revises: e49f4636c467
Create Date: 2020-04-30 23:22:11.076014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270413bf4fa4'
down_revision = 'e49f4636c467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
